(()=>{'use strict';const root=document.querySelector('#bb-coretox');if(!root||root.dataset.ready)return;root.dataset.ready='true';const reduced=matchMedia('(prefers-reduced-motion: reduce)'),connection=navigator.connection,hero=root.querySelector('.hero'),video=root.querySelector('video'),neuro=root.querySelector('.neuro'),gallery=root.querySelector('.clinic-gallery'),motions=[...root.querySelectorAll('.motion')],visible=new Map(motions.map(e=>[e,false]));let pageHidden=false,pending=false,stage=0,photo=0,stepTimer=null,photoTimer=null,pointer=null;const limited=()=>document.hidden||pageHidden||reduced.matches||!!connection?.saveData,runs=e=>visible.get(e)&&!limited();
function playback(){if(runs(hero)){if(!video.src)video.src=video.dataset.src;if(video.paused&&!pending){pending=true;video.play().catch(()=>{}).finally(()=>{pending=false;if(!runs(hero))video.pause()})}}else video.pause()}
video.addEventListener('error',()=>{video.hidden=true});
const tabs=[...root.querySelectorAll('[role=tab]')];function setStage(i,focus=false){stage=(i+tabs.length)%tabs.length;neuro.dataset.stage=String(stage);tabs.forEach((t,n)=>{t.setAttribute('aria-selected',String(n===stage));t.tabIndex=n===stage?0:-1;root.querySelector('#'+t.getAttribute('aria-controls')).hidden=n!==stage});if(focus)tabs[stage].focus()}
function scheduleSteps(){clearTimeout(stepTimer);stepTimer=null;if(runs(neuro))stepTimer=setTimeout(()=>{if(runs(neuro))setStage(stage+1);scheduleSteps()},5200)}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>{setStage(i);scheduleSteps()});t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=i+1;if(e.key==='ArrowLeft')n=i-1;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();setStage(n,true);scheduleSteps()}})});
const area=root.querySelector('.face-panel'),areaButtons=[...root.querySelectorAll('.area-button')];areaButtons.forEach((b,i)=>{b.addEventListener('click',()=>{area.dataset.area=b.dataset.area;root.querySelector('.area-caption').textContent=b.querySelector('span').textContent;areaButtons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowDown'||e.key==='ArrowRight')n=(i+1)%areaButtons.length;if(e.key==='ArrowUp'||e.key==='ArrowLeft')n=(i+areaButtons.length-1)%areaButtons.length;if(n!==undefined){e.preventDefault();areaButtons[n].click();areaButtons[n].focus()}})});
const shots=[...root.querySelectorAll('.clinic-shot')];function selectPhoto(n){photo=(n+shots.length)%shots.length;gallery.dataset.index=String(photo);shots.forEach((s,i)=>{s.classList.toggle('active',i===photo);s.setAttribute('aria-hidden',String(i!==photo))})}function schedulePhotos(){clearTimeout(photoTimer);photoTimer=null;if(runs(gallery))photoTimer=setTimeout(()=>{if(runs(gallery))selectPhoto(photo+1);schedulePhotos()},4800)}
gallery.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=photo+1;if(e.key==='ArrowLeft')n=photo-1;if(e.key==='Home')n=0;if(e.key==='End')n=shots.length-1;if(n!==undefined){e.preventDefault();selectPhoto(n);schedulePhotos()}});gallery.addEventListener('pointerdown',e=>pointer={x:e.clientX,y:e.clientY});gallery.addEventListener('pointerup',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4){selectPhoto(photo+(dx<0?1:-1));schedulePhotos()}});gallery.addEventListener('pointercancel',()=>pointer=null);
function sync(){for(const e of motions)e.dataset.motion=runs(e)?'playing':'paused';playback();scheduleSteps();schedulePhotos()}
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const e of entries){visible.set(e.target,e.isIntersecting);if(e.target===gallery&&e.isIntersecting)shots.forEach(s=>s.querySelector('img').loading='eager')}sync()},{threshold:.1});motions.forEach(e=>observer.observe(e))}else motions.forEach(e=>visible.set(e,true));document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);connection?.addEventListener?.('change',sync);window.addEventListener('pagehide',()=>{pageHidden=true;sync()});window.addEventListener('pageshow',()=>{pageHidden=false;sync()});setStage(0);selectPhoto(0);sync();})();
