(()=>{'use strict';const root=document.querySelector('#bb-cinderella');if(!root)return;const reduced=matchMedia('(prefers-reduced-motion:reduce)'),allowed=()=>!document.hidden&&!reduced.matches&&!navigator.connection?.saveData,motions=[...root.querySelectorAll('.cin-motion')],gallery=root.querySelector('.clinic-gallery'),shots=[...gallery.querySelectorAll('.clinic-shot')];let photo=0,visible=false,timer=null,pointer=null;
function show(n){photo=(n+shots.length)%shots.length;shots.forEach((s,i)=>{s.classList.toggle('active',i===photo);s.setAttribute('aria-hidden',String(i!==photo))});gallery.dataset.index=String(photo)}
function schedule(){clearTimeout(timer);timer=null;if(allowed()&&visible&&!gallery.matches(':focus-within'))timer=setTimeout(()=>{show(photo+1);schedule()},4800)}
function sync(){motions.forEach(e=>e.dataset.motion=allowed()&&e.dataset.visible==='true'?'playing':'paused');schedule()}
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.target===gallery){visible=e.isIntersecting;if(visible)shots.forEach(s=>s.querySelector('img').loading='eager')}else e.target.dataset.visible=String(e.isIntersecting)}sync()},{threshold:.08});motions.forEach(e=>observer.observe(e));observer.observe(gallery);
gallery.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=photo+1;if(e.key==='ArrowLeft')n=photo-1;if(e.key==='Home')n=0;if(e.key==='End')n=shots.length-1;if(n!==undefined){e.preventDefault();show(n);schedule()}});gallery.addEventListener('focusin',schedule);gallery.addEventListener('focusout',()=>queueMicrotask(schedule));gallery.addEventListener('pointerdown',e=>pointer={x:e.clientX,y:e.clientY});gallery.addEventListener('pointerup',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4){show(photo+(dx<0?1:-1));schedule()}});gallery.addEventListener('pointercancel',()=>pointer=null);
const tabs=[...root.querySelectorAll('[role=tab]')];function select(index,focus=false){tabs.forEach((t,i)=>{t.setAttribute('aria-selected',String(i===index));t.tabIndex=i===index?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=i!==index});if(focus)tabs[index].focus()}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>select(i));t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();select(n,true)}})});
document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);navigator.connection?.addEventListener?.('change',sync);window.addEventListener('pagehide',()=>clearTimeout(timer));window.addEventListener('pageshow',sync);show(0);sync();})();
