(()=>{'use strict';const root=document.querySelector('#bb-filler');if(!root)return;const reduced=matchMedia('(prefers-reduced-motion:reduce)'),saveData=()=>!!navigator.connection?.saveData,hero=root.querySelector('.fill-hero'),gallery=root.querySelector('.clinic-gallery'),shots=[...root.querySelectorAll('.clinic-shot')];let visible=false,photo=0,timer=null,pointer=null;
const allowed=()=>!document.hidden&&!reduced.matches&&!saveData();
function show(n){photo=(n+shots.length)%shots.length;shots.forEach((s,i)=>{s.classList.toggle('active',i===photo);s.setAttribute('aria-hidden',String(i!==photo))});gallery.dataset.index=String(photo)}
function schedule(){clearTimeout(timer);timer=null;if(allowed()&&visible&&!gallery.matches(':focus-within'))timer=setTimeout(()=>{show(photo+1);schedule()},4800)}
function sync(){hero.dataset.motion=allowed()&&hero.dataset.visible==='true'?'playing':'paused';schedule()}
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.target===gallery){visible=e.isIntersecting;if(visible)shots.forEach(s=>s.querySelector('img').loading='eager')}else hero.dataset.visible=String(e.isIntersecting)}sync()},{threshold:.1});observer.observe(hero);observer.observe(gallery);
gallery.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=photo+1;if(e.key==='ArrowLeft')n=photo-1;if(e.key==='Home')n=0;if(e.key==='End')n=shots.length-1;if(n!==undefined){e.preventDefault();show(n);schedule()}});gallery.addEventListener('focusin',schedule);gallery.addEventListener('focusout',()=>queueMicrotask(schedule));gallery.addEventListener('pointerdown',e=>pointer={x:e.clientX,y:e.clientY});gallery.addEventListener('pointerup',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4){show(photo+(dx<0?1:-1));schedule()}});gallery.addEventListener('pointercancel',()=>pointer=null);
const buttons=[...root.querySelectorAll('.fill-area-button')];function area(i,focus=false){buttons.forEach((b,n)=>b.setAttribute('aria-pressed',String(i===n)));root.querySelectorAll('[data-region]').forEach(p=>{p.toggleAttribute('hidden',p.dataset.region!==buttons[i].dataset.area)});root.querySelector('.fill-area-label').textContent=buttons[i].querySelector('span').textContent;if(focus)buttons[i].focus()}
buttons.forEach((b,i)=>{b.addEventListener('click',()=>area(i));b.addEventListener('keydown',e=>{let n;if(['ArrowRight','ArrowDown'].includes(e.key))n=(i+1)%buttons.length;if(['ArrowLeft','ArrowUp'].includes(e.key))n=(i+buttons.length-1)%buttons.length;if(n!==undefined){e.preventDefault();area(n,true)}})});
document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);navigator.connection?.addEventListener?.('change',sync);window.addEventListener('pagehide',()=>clearTimeout(timer));window.addEventListener('pageshow',sync);show(0);area(0);sync();})();
