(()=>{'use strict';const root=document.querySelector('#bb-xeomin');if(!root||root.dataset.ready)return;root.dataset.ready='true';const reduced=matchMedia('(prefers-reduced-motion: reduce)'),connection=navigator.connection,hero=root.querySelector('.xe-hero'),video=root.querySelector('video'),neuro=root.querySelector('.neuro'),gallery=root.querySelector('.clinic-gallery'),motions=[...root.querySelectorAll('.motion')],visible=new Map(motions.map(e=>[e,false]));let pageHidden=false,pending=false,stage=0,photo=0,stepTimer=null,photoTimer=null,pointer=null;const limited=()=>document.hidden||pageHidden||reduced.matches||!!connection?.saveData,runs=e=>visible.get(e)&&!limited();
let heroFrame=0,heroTimer=null;
const ready=i=>i?.complete&&i.naturalWidth>0&&i.dataset.decoded==='true',heroFrames=[...hero.querySelectorAll('.xe-hero-frame')],mechFrames=[...neuro.querySelectorAll('.xe-mech-frame')],stepGroup=root.querySelector('.mechanism-steps');
function prepareImage(img,onReady){const decode=()=>{const finish=()=>{if(img.naturalWidth){img.dataset.decoded='true';onReady()}};if(img.decode)img.decode().then(finish,()=>{});else finish()};img.addEventListener('load',decode);if(img.complete&&img.naturalWidth)decode()}
function setHero(i){if(!ready(heroFrames[i]))return;heroFrame=i;hero.dataset.heroFrame=String(i)}
function playback(){clearTimeout(heroTimer);heroTimer=null;if(runs(hero))heroTimer=setTimeout(()=>{if(runs(hero))setHero((heroFrame+1)%heroFrames.length);playback()},6800)}
heroFrames.forEach((img,i)=>{prepareImage(img,()=>{if(!ready(heroFrames[heroFrame]))setHero(i)});img.addEventListener('error',()=>{const n=heroFrames.findIndex(ready);if(n>=0)setHero(n)})});
function selectMechanismImage(i){if(ready(mechFrames[i]))neuro.dataset.imageFrame=String(i)}
mechFrames.forEach((img,i)=>{prepareImage(img,()=>{if(i===stage||!ready(mechFrames[Number(neuro.dataset.imageFrame||0)]))selectMechanismImage(i)});img.addEventListener('error',()=>{const n=mechFrames.findIndex(ready);if(n>=0)selectMechanismImage(n)})});
const tabs=[...root.querySelectorAll('.step-tabs [role=tab]')];function setStage(i,focus=false){stage=(i+tabs.length)%tabs.length;neuro.dataset.stage=String(stage);selectMechanismImage(stage);tabs.forEach((t,n)=>{t.setAttribute('aria-selected',String(n===stage));t.tabIndex=n===stage?0:-1;root.querySelector('#'+t.getAttribute('aria-controls')).hidden=n!==stage});if(focus)tabs[stage].focus()}
function scheduleSteps(){clearTimeout(stepTimer);stepTimer=null;if(runs(neuro)&&!stepGroup.contains(document.activeElement))stepTimer=setTimeout(()=>{if(runs(neuro)&&!stepGroup.contains(document.activeElement))setStage(stage+1);scheduleSteps()},5200)}
stepGroup.addEventListener('focusin',scheduleSteps);stepGroup.addEventListener('focusout',()=>queueMicrotask(scheduleSteps));
tabs.forEach((t,i)=>{t.addEventListener('click',()=>{setStage(i);scheduleSteps()});t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=i+1;if(e.key==='ArrowLeft')n=i-1;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();setStage(n,true);scheduleSteps()}})});
const area=root.querySelector('.face-panel'),areaGroup=root.querySelector('.area-options'),areaButtons=[...root.querySelectorAll('.area-button')];let areaIndex=0,areaTimer=null;
function setArea(i){areaIndex=(i+areaButtons.length)%areaButtons.length;const b=areaButtons[areaIndex];area.dataset.area=b.dataset.area;root.querySelector('.area-caption').textContent=b.querySelector('span').textContent;areaButtons.forEach((x,n)=>x.setAttribute('aria-pressed',String(n===areaIndex)))}
function scheduleAreas(){clearTimeout(areaTimer);areaTimer=null;if(runs(area)&&!areaGroup.contains(document.activeElement))areaTimer=setTimeout(()=>{areaTimer=null;if(runs(area)&&!areaGroup.contains(document.activeElement))setArea(areaIndex+1);scheduleAreas()},5000)}
areaGroup.addEventListener('focusin',scheduleAreas);areaGroup.addEventListener('focusout',()=>queueMicrotask(scheduleAreas));
areaButtons.forEach((b,i)=>{b.addEventListener('click',()=>{setArea(i);scheduleAreas()});b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowDown'||e.key==='ArrowRight')n=(i+1)%areaButtons.length;if(e.key==='ArrowUp'||e.key==='ArrowLeft')n=(i+areaButtons.length-1)%areaButtons.length;if(n!==undefined){e.preventDefault();areaButtons[n].click();areaButtons[n].focus()}})});
const shots=[...root.querySelectorAll('.clinic-shot')];function selectPhoto(n){photo=(n+shots.length)%shots.length;gallery.dataset.index=String(photo);shots.forEach((s,i)=>{s.classList.toggle('active',i===photo);s.setAttribute('aria-hidden',String(i!==photo))})}function schedulePhotos(){clearTimeout(photoTimer);photoTimer=null;if(runs(gallery))photoTimer=setTimeout(()=>{if(runs(gallery))selectPhoto(photo+1);schedulePhotos()},4800)}
gallery.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=photo+1;if(e.key==='ArrowLeft')n=photo-1;if(e.key==='Home')n=0;if(e.key==='End')n=shots.length-1;if(n!==undefined){e.preventDefault();selectPhoto(n);schedulePhotos()}});gallery.addEventListener('pointerdown',e=>pointer={x:e.clientX,y:e.clientY});gallery.addEventListener('pointerup',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.4){selectPhoto(photo+(dx<0?1:-1));schedulePhotos()}});gallery.addEventListener('pointercancel',()=>pointer=null);
function sync(){for(const e of motions)e.dataset.motion=runs(e)?'playing':'paused';playback();scheduleSteps();schedulePhotos();scheduleAreas()}
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const e of entries){visible.set(e.target,e.isIntersecting);if(e.isIntersecting&&(e.target===gallery||e.target===neuro))e.target.querySelectorAll('img').forEach(i=>i.loading='eager')}sync()},{threshold:.1});motions.forEach(e=>observer.observe(e))}else motions.forEach(e=>visible.set(e,true));document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);connection?.addEventListener?.('change',sync);window.addEventListener('pagehide',()=>{pageHidden=true;sync()});window.addEventListener('pageshow',()=>{pageHidden=false;sync()});setStage(0);selectPhoto(0);setArea(0);const firstReady=heroFrames.findIndex(ready);if(firstReady>=0)setHero(firstReady);sync();})();
