/* Page-local motion. Existing model identity, copy, footer navigation and staff state remain intact. */
(()=>{'use strict';
 const root=document.querySelector('#bb-cellredm');if(!root||root.dataset.motionR02)return;root.dataset.motionR02='true';
 const reduced=matchMedia('(prefers-reduced-motion:reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)'),allowed=()=>!document.hidden&&!reduced.matches&&!navigator.connection?.saveData;
 const product=root.querySelector('.cr-product-visual'),network=root.querySelector('.cr-network'),spec=root.querySelector('.cr-spec'),editorial=root.querySelector('.cr-editorial'),hero=root.querySelector('.cr-hero');
 if(product){const img=product.querySelector('img');if(img){const stage=document.createElement('div');stage.className='cr-product-stage';img.before(stage);stage.append(img);const light=document.createElement('span');light.className='cr-product-gloss';light.setAttribute('aria-hidden','true');stage.append(light)}}
 if(network){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 600');svg.setAttribute('aria-hidden','true');svg.setAttribute('focusable','false');svg.classList.add('cr-ecm-flow');
  const paths=['M80 315 C120 100 390 115 505 350 S235 575 100 340','M170 90 C455 140 550 390 325 500 S50 335 170 90','M90 380 C260 180 510 180 495 365 S230 570 90 380'];
  for(const d of paths)for(const kind of ['cr-flow-track','cr-flow-light']){const p=document.createElementNS(ns,'path');p.setAttribute('d',d);p.setAttribute('pathLength','600');p.setAttribute('class',kind);svg.append(p)}
  for(const [cx,cy] of [[155,200],[465,375],[290,497]]){const c=document.createElementNS(ns,'circle');c.setAttribute('cx',cx);c.setAttribute('cy',cy);c.setAttribute('r','4');svg.append(c)}network.append(svg);network.dataset.focus='1';
 }
 let panelAnimation=null;
 const card=root.querySelector('.cr-tab-card');if(card){new MutationObserver(()=>{const tabs=[...card.querySelectorAll('[role=tab]')],i=tabs.findIndex(t=>t.getAttribute('aria-selected')==='true');if(i<0)return;card.style.setProperty('--cr-tab-progress',String((i+1)/tabs.length));if(network)network.dataset.focus=String(i+1);const panel=card.querySelector('[role=tabpanel]:not([hidden])');panelAnimation?.cancel();if(panel&&allowed())panelAnimation=panel.animate([{opacity:.45,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:420,easing:'cubic-bezier(.2,.7,.2,1)'})}).observe(card,{subtree:true,attributes:true,attributeFilter:['aria-selected']})}
 function pointerDepth(el,xName,yName,range){if(!el)return;el.addEventListener('pointermove',e=>{if(!allowed()||!fine.matches)return;const r=el.getBoundingClientRect();el.style.setProperty(xName,((e.clientX-r.left)/r.width-.5)*range+'px');el.style.setProperty(yName,((e.clientY-r.top)/r.height-.5)*range+'px')},{passive:true});el.addEventListener('pointerleave',()=>{el.style.setProperty(xName,'0px');el.style.setProperty(yName,'0px')})}
 pointerDepth(product,'--cr-tilt-x','--cr-tilt-y',16);pointerDepth(hero,'--cr-model-x','--cr-model-y',12);
 let canvas=null,ctx=null,width=0,height=0,frame=0,visible=false,last=0,phase=0,editorialVisible=false,scrollFrame=0;
 const beads=Array.from({length:18},(_,i)=>({x:((i*43+17)%100)/100,y:((i*31+7)%100)/100,r:3+(i%5)*2,speed:.12+(i%4)*.025}));
 if(spec){canvas=document.createElement('canvas');canvas.className='cr-micro-field';canvas.setAttribute('aria-hidden','true');spec.querySelector('.cr-spec-content')?.prepend(canvas);ctx=canvas.getContext('2d');
  const resize=()=>{const r=canvas.getBoundingClientRect();width=r.width;height=r.height;const dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx?.setTransform(dpr,0,0,dpr,0,0)};new ResizeObserver(resize).observe(canvas);resize();
 }
 function paint(t){frame=0;if(!allowed()||!visible||!ctx){last=0;return}const dt=last?Math.min((t-last)/1000,.05):0;last=t;phase+=dt;ctx.clearRect(0,0,width,height);
  for(const b of beads){const x=(b.x+Math.sin(phase*b.speed+b.r)*.035)*width,y=(b.y+Math.cos(phase*b.speed+b.x*6)*.05)*height;const g=ctx.createRadialGradient(x-b.r*.3,y-b.r*.3,0,x,y,b.r);g.addColorStop(0,'rgba(255,255,255,.95)');g.addColorStop(.5,'rgba(220,179,210,.5)');g.addColorStop(1,'rgba(150,98,146,.08)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,b.r,0,Math.PI*2);ctx.fill()}
  frame=requestAnimationFrame(paint);
 }
 function scrollType(){scrollFrame=0;if(!editorial||!editorialVisible||!allowed())return;const r=editorial.getBoundingClientRect(),p=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height)));editorial.style.setProperty('--cr-type-y',((.5-p)*38)+'px');editorial.style.setProperty('--cr-type-scale',String(.96+p*.065))}
 function sync(){if(frame){cancelAnimationFrame(frame);frame=0}last=0;if(allowed()&&visible&&ctx)frame=requestAnimationFrame(paint);if(!allowed()){panelAnimation?.cancel();editorial?.style.setProperty('--cr-type-y','0px');editorial?.style.setProperty('--cr-type-scale','1');hero?.style.setProperty('--cr-model-x','0px');hero?.style.setProperty('--cr-model-y','0px');product?.style.setProperty('--cr-tilt-x','0px');product?.style.setProperty('--cr-tilt-y','0px')}else scrollType()}
 const observer=new IntersectionObserver(es=>{for(const e of es){if(e.target===spec)visible=e.isIntersecting;if(e.target===editorial)editorialVisible=e.isIntersecting}sync()},{threshold:.06});if(spec)observer.observe(spec);if(editorial)observer.observe(editorial);
 addEventListener('scroll',()=>{if(editorialVisible&&allowed()&&!scrollFrame)scrollFrame=requestAnimationFrame(scrollType)},{passive:true});document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);navigator.connection?.addEventListener?.('change',sync);addEventListener('pagehide',()=>{cancelAnimationFrame(frame);cancelAnimationFrame(scrollFrame);frame=0;scrollFrame=0;last=0});addEventListener('pageshow',sync);sync();
})();
