(()=>{'use strict';const root=document.getElementById('bb-inmode');if(!root)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)'),connection=navigator.connection;const allowed=()=>!document.hidden&&!reduced.matches&&!connection?.saveData;const motion=[...root.querySelectorAll('.im-motion')],visible=new Set();const tabs=[...root.querySelectorAll('.im-tabs [role=tab]')],panels=tabs.map(t=>document.getElementById(t.getAttribute('aria-controls'))),skin=root.querySelector('.im-skin');let active=0,tabTimer=0,holdUntil=0;
function choose(n,focus=false){active=(n+tabs.length)%tabs.length;tabs.forEach((t,i)=>{t.setAttribute('aria-selected',String(i===active));t.tabIndex=i===active?0:-1;panels[i].hidden=i!==active;});skin.dataset.mode=tabs[active].dataset.mode;skin.querySelector('.im-skin-mode').textContent=tabs[active].textContent;if(focus)tabs[active].focus();}
function scheduleTabs(){clearTimeout(tabTimer);if(!allowed()||!visible.has(skin))return;tabTimer=setTimeout(()=>{const focused=root.querySelector('.im-principle').contains(document.activeElement);if(Date.now()>holdUntil&&!focused&&!root.querySelector('.im-principle').matches(':hover'))choose(active+1);scheduleTabs();},4500);}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>{holdUntil=Date.now()+15000;choose(i);scheduleTabs();});tab.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=i+1;if(e.key==='ArrowLeft')n=i-1;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();holdUntil=Date.now()+15000;choose(n,true);scheduleTabs();}});});
const face=root.querySelector('.im-face'),areaButtons=[...root.querySelectorAll('.im-area-options button')],names={chin:'턱밑',jaw:'페이스라인',firm:'피부 탄력'};areaButtons.forEach(b=>b.addEventListener('click',()=>{areaButtons.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));face.dataset.area=b.dataset.area;face.querySelector('.im-face-label').textContent=names[b.dataset.area];}));
const gallery=root.querySelector('.clinic-gallery'),shots=gallery?[...gallery.querySelectorAll('.clinic-shot')]:[];let galleryIndex=0,galleryTimer=0,touch=null,galleryVisible=false;
function showShot(n){if(!shots.length)return;galleryIndex=(n+shots.length)%shots.length;shots.forEach((s,i)=>{s.classList.toggle('active',i===galleryIndex);s.setAttribute('aria-hidden',String(i!==galleryIndex));});}
function scheduleGallery(){clearTimeout(galleryTimer);if(!gallery||!galleryVisible||!allowed()||gallery.matches(':focus-within'))return;galleryTimer=setTimeout(()=>{showShot(galleryIndex+1);scheduleGallery();},4800);}
if(gallery){gallery.tabIndex=0;gallery.setAttribute('aria-label','원내 공간 사진. 왼쪽·오른쪽 방향키로 이동');showShot(0);gallery.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();showShot(e.key==='Home'?0:e.key==='End'?shots.length-1:galleryIndex+(e.key==='ArrowLeft'?-1:1));scheduleGallery();}});gallery.addEventListener('focusin',scheduleGallery);gallery.addEventListener('focusout',()=>setTimeout(scheduleGallery,0));gallery.addEventListener('touchstart',e=>{if(e.touches.length===1)touch=[e.touches[0].clientX,e.touches[0].clientY];},{passive:true});gallery.addEventListener('touchend',e=>{if(!touch||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-touch[0],dy=e.changedTouches[0].clientY-touch[1];touch=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){showShot(galleryIndex+(dx<0?1:-1));scheduleGallery();}},{passive:true});}
function policy(){motion.forEach(e=>e.dataset.motion=allowed()&&visible.has(e)?'playing':'paused');scheduleTabs();scheduleGallery();}
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting)visible.add(entry.target);else visible.delete(entry.target);if(entry.target===gallery)galleryVisible=entry.isIntersecting;}policy();},{threshold:.08});motion.forEach(e=>observer.observe(e));if(gallery)observer.observe(gallery);}else{motion.forEach(e=>visible.add(e));galleryVisible=true;}
document.addEventListener('visibilitychange',policy);reduced.addEventListener('change',policy);connection?.addEventListener?.('change',policy);window.addEventListener('pagehide',()=>{clearTimeout(tabTimer);clearTimeout(galleryTimer);motion.forEach(e=>e.dataset.motion='paused');});window.addEventListener('pageshow',policy);policy();})();
